export { default as anime } from './anime.js'
export { default as manga } from './manga.js'
export { default as character } from './character.js'
export { default as c } from './character.js' 
export { default as m } from './manga.js'
export { default as a } from './anime.js'

export { default as ignore } from './ignore.js'
export { default as ignoreremove } from './ignoreremove.js'
export { default as ignorelist } from './ignorelist.js'
export { default as help } from './help.js'